# -*- mode: python ; coding: utf-8 -*-

import os

block_cipher = None

module_datas = []
modules_dir = 'modules'
for root, dirs, files in os.walk(modules_dir):
    for f in files:
        full = os.path.join(root, f)
        module_datas.append((full, os.path.dirname(full)))

a = Analysis(['M9A_Update_Assistant.py'],
             pathex=[],
             binaries=[],
             datas=[] + module_datas,
             hiddenimports=['requests', 'socks', 'colorama',
                           'modules.config_manager',
                           'modules.github_release_client',
                           'modules.download_manager',
                           'modules.zip_manager',
                           'modules.m9a_updater',
                           'modules.self_updater'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[
                 'altgraph',
                 'astroid',
                 'atomicwrites',
                 'attrs',
                 'babel',
                 'bcrypt',
                 'black',
                 'blinker',
                 'boto',
                 'boto3',
                 'botocore',
                 'cairo',
                 'cffi',
                 'cryptography',
                 'curses',
                 'distutils',
                 'docutils',
                 'easy_install',
                 'faulthandler',
                 'flask',
                 'future',
                 'gevent',
                 'greenlet',
                 'h5py',
                 'idlelib',
                 'ipykernel',
                 'IPython',
                 'isort',
                 'jinja2',
                 'jupyter',
                 'lib2to3',
                 'markupsafe',
                 'matplotlib',
                 'mock',
                 'multiprocessing',
                 'nacl',
                 'numpy',
                 'paramiko',
                 'pexpect',
                 'pickle',
                 'pickleshare',
                 'PIL',
                 'pkg_resources',
                 'prompt_toolkit',
                 'psutil',
                 'ptyprocess',
                 'pyasn1',
                 'pycodestyle',
                 'pycparser',
                 'pyflakes',
                 'pygame',
                 'pygments',
                 'pylint',
                 'pynacl',
                 'PyQt4',
                 'PyQt5',
                 'PyQt6',
                 'PySide2',
                 'PySide6',
                 'pytest',
                 'scipy',
                 'setuptools',
                 'shelve',
                 'sphinx',
                 'sqlalchemy',
                 'subprocess',
                 'tkinter',
                 'toml',
                 'tornado',
                 'traitlets',
                 'unittest',
                 'wcwidth',
                 'wheel',
                 'wx',
                 'xml',
                 'xmlrpc',
                 'yaml',
                 'zmq',
             ],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)


exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='M9A_Update_Assistant',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=['python3*.dll', 'VCRUNTIME*.dll', 'api-ms-win-*.dll'],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None)
