name: 使用 Nuitka 构建

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检查代码库
      - name: Check-out repository
        uses: actions/checkout@v4

      # 检查当前 Python 版本
      - name: Check Python
        id: check_python
        shell: bash
        run: |
          # 检查 Python 版本
          PYTHON_VERSION=$(python --version 2>&1 || python3 --version 2>&1)
          echo "Detected Python version: $PYTHON_VERSION"
          
          if echo "$PYTHON_VERSION" | grep -i "python 3\.12"; then
            echo "python_version=3.12" >> $GITHUB_OUTPUT
            echo "skip_setup=true" >> $GITHUB_OUTPUT
          else
            echo "skip_setup=false" >> $GITHUB_OUTPUT
          fi

      # 设置 Python 环境（仅当当前版本不是 3.12 时）
      - name: Setup Python
        if: steps.check_python.outputs.skip_setup != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      # 安装依赖
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 使用 Nuitka 编译为可执行文件
      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: M9A_Update_Assistant.py
          mode: onefile
          windows-console-mode: force
          assume-yes-for-downloads: true
          follow-imports: true
          output-dir: build
          include-package: requests,PySocks
          no-deployment-flag: self-execution
          nofollow-import-to: '*.tests'

      # 上传编译后的可执行文件
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ALAS_Logs_Archive-Nuitka-${{ github.ref_name }}
          path: build/ALAS_Logs_Archive.exe
          retention-days: 7